language: csharp
sudo: required
dist: xenial
solution: CAP.sln
dotnet: 2.2
mono: none

#matrix:
#  include:
#  - dotnet: 2.2
#  - os: linux
#    dist: trusty # Ubuntu 14.04
#    sudo: required
#  - os: osx
#    osx_image: xcode8.3 # macOS 10.12
    
# Run the build script

script:
 - dotnet tool install --global FlubuCore.GlobalTool --version 4.2.8
 - flubu build test