language: csharp
sudo: required
dist: xenial
solution: CAP.sln
dotnet: 3.1.100
mono: none
env:
 - Cap_MySql_ConnectionString="Server=127.0.0.1;Database=cap_test;Uid=root;Pwd=;Allow User Variables=True;SslMode=none"

services:
 - mysql

script:
 - export PATH="$PATH:$HOME/.dotnet/tools"
 - dotnet tool install --global FlubuCore.GlobalTool --version 5.1.1
 - flubu build tests