language: csharp
sudo: required
dist: trusty
mono: none
dotnet: 1.0.0

install:
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rvm get stable; brew update; brew install openssl; fi
os:
  - linux
  - osx
osx_image: xcode7.3
before_script:
  - chmod a+x ./build.sh
script:
  - ./build.sh
notifications:
  email: false
