# Project information
site_name: CAP
site_url: http://cap.dotnetcore.xyz
site_description: A distributed transaction solution in micro-service base on eventually consistency, also an eventbus with Outbox pattern.
site_author: CAP Team

repo_name: 'GitHub'
repo_url: 'https://github.com/dotnetcore/CAP'
edit_uri: 'edit/master/docs/content'
docs_dir: 'content'

# Copyright
copyright: Copyright &copy; 2017 <a href="https://github.com/dotnetcore">NCC</a>, Maintained by the <a href="/about/contact-us/#cap-team">CAP Team</a>.


#theme: material
theme:
  name: 'material'
  palette:
    primary: 'deep purple'
    accent: 'indigo'  
  language: 'en'
  include_sidebar: true
  logo: 'img/logo.svg'
  favicon: 'img/favicon.ico'
  feature:
    tabs: true  
  i18n:
    prev: 'Previous'
    next: 'Next'

#Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/dotnetcore/CAP'
    - type: 'twitter'
      link: 'https://twitter.com/ncc_community'
    - type: 'weibo'
      link: 'https://weibo.com/dotnetcore'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: true
      linenums: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: dotnetcore
      repo: cap
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
    - Home: index.md
    - Documentation:
      - Getting Stared:
          - Quick Start: user-guide/en/getting-started/quick-start.md
          - Introduction: user-guide/en/getting-started/introduction.md
          - Contributing: user-guide/en/getting-started/contributing.md    
      - CAP:
          - Configuration: user-guide/en/cap/configuration.md
          - Messaging: user-guide/en/cap/messaging.md
          - Sagas: user-guide/en/cap/sagas.md
          - Serialization: user-guide/en/cap/serialization.md
          - Transactions: user-guide/en/cap/transactions.md
          - Idempotence: user-guide/en/cap/idempotence.md
      - Transports:
          - General: user-guide/en/transports/general.md
          - RabbitMQ: user-guide/en/transports/rabbitmq.md
          - Apache Kafka®: user-guide/en/transports/kafka.md
          - Azure Service Bus: user-guide/en/transports/azure-service-bus.md
          - In-Memory Queue: user-guide/en/transports/in-memory-queue.md
      - Persistent:
          - General: user-guide/en/persistent/general.md
          - SQL Server: user-guide/en/persistent/sqlserver.md
          - MySQL: user-guide/en/persistent/mysql.md
          - PostgreSql: user-guide/en/persistent/postgresql.md
          - MongoDB: user-guide/en/persistent/mongodb.md
          - In-Memory: user-guide/en/persistent/in-memory-storage.md
      - Monitoring:
          - Dashboard: user-guide/en/monitoring/dashboard.md
          - Diagnostics: user-guide/en/monitoring/diagnostics.md
      - Samples:
          - Github: user-guide/en/samples/github.md
          - eShopOnContainers: user-guide/en/samples/eshoponcontainers.md
          - FAQ: user-guide/en/samples/faq.md
    - 文档（中文）:
      - 入门:
          - 快速开始: user-guide/zh/getting-started/quick-start.md
          - 介绍: user-guide/zh/getting-started/introduction.md
          - 贡献: user-guide/zh/getting-started/contributing.md    
      - CAP:
          - 配置: user-guide/zh/cap/configuration.md
          - 消息: user-guide/zh/cap/messaging.md
          - Sagas: user-guide/zh/cap/sagas.md
          - 序列化: user-guide/zh/cap/serialization.md
          - 传输: user-guide/zh/cap/transactions.md
          - 幂等性: user-guide/zh/cap/idempotence.md          
      - 传输:
          - 简介: user-guide/zh/transports/general.md
          - RabbitMQ: user-guide/zh/transports/rabbitmq.md
          - Apache Kafka®: user-guide/zh/transports/kafka.md
          - Azure Service Bus: user-guide/zh/transports/azure-service-bus.md
          - In-Memory Queue: user-guide/zh/transports/in-memory-queue.md
      - 持久化:
          - 简介: user-guide/zh/persistent/general.md
          - SQL Server: user-guide/zh/persistent/sqlserver.md
          - MySQL: user-guide/zh/persistent/mysql.md
          - PostgreSql: user-guide/zh/persistent/postgresql.md
          - MongoDB: user-guide/zh/persistent/mongodb.md
          - In-Memory: user-guide/zh/persistent/in-memory-storage.md
      - 监控:
          - Consul: user-guide/zh/monitoring/consul.md
          - Dashboard: user-guide/zh/monitoring/dashboard.md
          - Diagnostics: user-guide/zh/monitoring/diagnostics.md
          - 健康检查: user-guide/zh/monitoring/health-checks.md
          - Metrics: user-guide/zh/monitoring/metrics.md
      - 示例:
          - Github: user-guide/zh/samples/github.md
          - eShopOnContainers: user-guide/zh/samples/eshoponcontainers.md
          - FAQ: user-guide/zh/samples/faq.md
    - About:
      - Contact Us: about/contact-us.md
      - Release Notes: about/release-notes.md
      - License: about/license.md
